"""create shop table

Revision ID: 8444f7466e7f
Revises: 
Create Date: 2024-03-10 12:04:52.946027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8444f7466e7f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shops',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('wifi', sa.Integer(), nullable=True),
    sa.Column('seat', sa.Integer(), nullable=True),
    sa.Column('quiet', sa.Integer(), nullable=True),
    sa.Column('tasty', sa.Integer(), nullable=True),
    sa.Column('cheap', sa.Integer(), nullable=True),
    sa.Column('music', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('latitude', sa.Double(), nullable=True),
    sa.Column('longitude', sa.Double(), nullable=True),
    sa.Column('limited_time', sa.Boolean(), nullable=True),
    sa.Column('socket', sa.Boolean(), nullable=True),
    sa.Column('standing_desk', sa.Boolean(), nullable=True),
    sa.Column('mrt', sa.String(), nullable=True),
    sa.Column('open_time', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shops_mrt'), 'shops', ['mrt'], unique=False)
    op.create_index(op.f('ix_shops_name'), 'shops', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shops_name'), table_name='shops')
    op.drop_index(op.f('ix_shops_mrt'), table_name='shops')
    op.drop_table('shops')
    # ### end Alembic commands ###
