version: '3.7'
services: 
    elasticsearch:
        build:
          context: .
          dockerfile: Dockerfile.elasticsearch
        container_name: elasticsearch
        environment: 
        - discovery.type=single-node
        - ES_JAVA_OPTS=-Xms750m -Xmx750m
        - xpack.security.enabled=false
        ports: 
        - 9200:9200
        - 9300:9300
        networks: 
        - coffee_shop_finder_network
        volumes:
        - ./data:/usr/share/elasticsearch/data
    kibana:
        image: kibana:8.12.2
        container_name: kibana
        ports: 
        - 5601:5601
        networks:
        - coffee_shop_finder_network
        depends_on: 
        - elasticsearch
    logstash:
        container_name: logstash
        platform: linux/arm64
        build:
          context: .
          dockerfile: Dockerfile.logstash
        ports:
        - 5050:5050
        environment:
        - CONFIG_SUPPORT_ESCAPE=true
        - ELASTICSEARCH_URL=http://elasticsearch:9200
        depends_on:
        - elasticsearch
        volumes:
        - ./config:/usr/share/logstash/config
        - ./logstash_data:/usr/share/logstash/data
        networks:
        - coffee_shop_finder_network

volumes:
  elasticsearch_data:
    driver: local
networks:
  coffee_shop_finder_network:
    external: true