FROM docker.elastic.co/logstash/logstash:8.12.2

# copy postgresql jdbc driver to the logstash image
COPY ./bin/ /usr/share/logstash/logstash-core/lib/jars

# copy usersync pipeline to the logstash image
COPY config/ /usr/share/logstash/config/

CMD ["logstash", "-f", "/usr/share/logstash/config/usersync.conf"]